In [20]:
import tensorflow as tf
import numpy as np
import torch
X = torch.rand([4, 3])
W = torch.rand([3, 5])
y = torch.randperm(4)
num_train = X.shape[0]
score = X.mm(W)
x_t = torch.argmax(X)
x_t0 = torch.argmax(X, 1)
print(X, '\n', x_t, '\t', x_t0)
x_n = np.argmax(X)
x_n0 = np.argmax(X, 1)
print(X, '\n', x_n, '\t', x_n0)
x_f = tf.argmax(X)
x_f0 = tf.argmax(X, 1)
print(X, '\n', x_f, '\t', x_f0)
print(y)

tensor([[0.8455, 0.7791, 0.4064],
        [0.6842, 0.4369, 0.1254],
        [0.1584, 0.0212, 0.1811],
        [0.1894, 0.0117, 0.0020]]) 
 tensor(0) 	 tensor([0, 0, 2, 0])
tensor([[0.8455, 0.7791, 0.4064],
        [0.6842, 0.4369, 0.1254],
        [0.1584, 0.0212, 0.1811],
        [0.1894, 0.0117, 0.0020]]) 
 tensor(0) 	 tensor([0, 0, 2, 0])
tensor([[0.8455, 0.7791, 0.4064],
        [0.6842, 0.4369, 0.1254],
        [0.1584, 0.0212, 0.1811],
        [0.1894, 0.0117, 0.0020]]) 
 tf.Tensor([0 0 0], shape=(3,), dtype=int64) 	 tf.Tensor([0 0 2 0], shape=(4,), dtype=int64)
tensor([2, 0, 1, 3])


In [81]:
X0 = np.random.rand(4, 3)
W0 = np.random.rand(3, 5)
# torch use 'mm'; torch has attribute 'dot' but only cal in 1D. in mm X, or M neither can be np. 
#score0 = torch.mm(X, W)
score0 = X.mm(W0)
# numpy use 'dot', doesn't has attribute 'mm'. can use 'np dot torch'
score_np = X0.dot(W)
print(score0, '\n', score, '\n')
print(score_np)
print(X,'\n', X0, '\n')

TypeError: mm(): argument 'mat2' (position 1) must be Tensor, not numpy.ndarray

In [62]:
k = 0
a = [0.8455, 0.7791, 0.4064]
b = [0.5337, 0.7125, 0.4724]
for i, j in zip(a, b):
    k += i * j
    print(i, j, k)
print(k)
xx = 

0.8455 0.5337 0.45124335
0.7791 0.7125 1.0063521
0.4064 0.4724 1.19833546
1.19833546


In [33]:
y_pred = torch.argmax(score, 1)
print(y,'\n', y_pred, y_pred.shape)
#accu_t = np.mean(y_pred == y)
y_ab = y_pred - y
accu = 1 - torch.count_nonzero(y_ab) / num_train
print(accu)
#print((y_pred == y).mean())
print((y_pred == y).sum() / len(y_pred == y))
print(torch.sum(y_pred == y) / len(y_pred == y))

tensor([2, 0, 1, 3]) 
 tensor([2, 2, 2, 2]) torch.Size([4])
tensor(0.2500)
tensor(0.2500)
tensor(0.2500)
