In [91]:
import numpy as np
import torch

X = torch.rand([4, 3])
y = torch.randperm(4)
num_train = X.shape[0]
batch_size = 40
#dim = 2
print(X, '\n', y)

tensor([[0.2481, 0.6432, 0.3115],
        [0.8465, 0.3194, 0.5687],
        [0.9843, 0.0353, 0.4146],
        [0.3098, 0.9517, 0.3402]]) 
 tensor([0, 2, 1, 3])


In [76]:
X_batch = None
y_batch = None
num_chunck = batch_size * dim
length_X = X.shape[0] * X.shape[1]
length_y = len(y)
print(length_X, length_y)


xx = 0
yy = 0
indX = torch.randint(length_X, (batch_size, dim))
indy = torch.randint(length_y, (batch_size,))
for i in range(length_X // num_chunck):
    indX = torch.randint(xx, xx + num_chunck, (batch_size, dim))
    indy = torch.randint(yy, yy + num_chunck, (batch_size, 1))
    xx += num_chunck
    yy += num_chunck
    #X_batch = X[indX]
    #y_batch = y[indy]
    #print(X[indX])
    
print(indX, '\n', indy)
print(X, '\n', y_batch)

12 4
tensor([[2, 2],
        [3, 7],
        [3, 4],
        [3, 1]]) 
 tensor([[1],
        [5],
        [0],
        [3]])
tensor([[0.5657, 0.5069, 0.6903],
        [0.3055, 0.6574, 0.4924],
        [0.2904, 0.1416, 0.3989],
        [0.6245, 0.3383, 0.4088]]) 
 None


In [95]:
# data can be reused batch_size * dim, so dim can be any num
X_batch = None
y_batch = None

num_train = X.shape[0]
num_dim = X.shape[1]
dim = num_dim
X_data = torch.flatten(X)
length_X_data = len(X_data)
#for i in range(batch_size):
ind_X = torch.randint(length_X_data, (batch_size * dim, ))
X_batch = X_data[ind_X].reshape([batch_size, dim])

print(X_batch)

tensor([[0.5687, 0.9517, 0.6432],
        [0.8465, 0.3194, 0.3115],
        [0.8465, 0.4146, 0.3194],
        [0.3194, 0.0353, 0.3194],
        [0.5687, 0.2481, 0.3194],
        [0.3098, 0.9843, 0.2481],
        [0.3194, 0.3098, 0.9517],
        [0.3194, 0.5687, 0.8465],
        [0.5687, 0.3098, 0.3194],
        [0.9517, 0.6432, 0.8465],
        [0.3194, 0.2481, 0.3115],
        [0.9517, 0.3194, 0.9517],
        [0.4146, 0.9517, 0.6432],
        [0.6432, 0.6432, 0.8465],
        [0.9517, 0.5687, 0.0353],
        [0.9517, 0.3098, 0.2481],
        [0.4146, 0.6432, 0.4146],
        [0.9843, 0.3402, 0.3194],
        [0.9517, 0.8465, 0.2481],
        [0.5687, 0.2481, 0.2481],
        [0.4146, 0.3098, 0.2481],
        [0.9843, 0.4146, 0.9843],
        [0.3098, 0.6432, 0.3098],
        [0.4146, 0.3194, 0.3194],
        [0.6432, 0.6432, 0.3098],
        [0.4146, 0.3098, 0.2481],
        [0.3098, 0.5687, 0.0353],
        [0.3194, 0.3194, 0.3115],
        [0.8465, 0.6432, 0.5687],
        [0.568

In [98]:
# abstract n batches form N total num_train.
X_batch = None
y_batch = None
num_train = X.shape[0]
dim = X.shape[1]

n = torch.randint(num_train, (batch_size,))
X_batch = X[n, :]
y_batch = y[n]

print(X_batch, '\n', y_batch)

tensor([[0.9843, 0.0353, 0.4146],
        [0.2481, 0.6432, 0.3115],
        [0.9843, 0.0353, 0.4146],
        [0.2481, 0.6432, 0.3115],
        [0.8465, 0.3194, 0.5687],
        [0.3098, 0.9517, 0.3402],
        [0.3098, 0.9517, 0.3402],
        [0.3098, 0.9517, 0.3402],
        [0.2481, 0.6432, 0.3115],
        [0.2481, 0.6432, 0.3115],
        [0.9843, 0.0353, 0.4146],
        [0.9843, 0.0353, 0.4146],
        [0.8465, 0.3194, 0.5687],
        [0.8465, 0.3194, 0.5687],
        [0.8465, 0.3194, 0.5687],
        [0.8465, 0.3194, 0.5687],
        [0.3098, 0.9517, 0.3402],
        [0.9843, 0.0353, 0.4146],
        [0.2481, 0.6432, 0.3115],
        [0.8465, 0.3194, 0.5687],
        [0.9843, 0.0353, 0.4146],
        [0.3098, 0.9517, 0.3402],
        [0.3098, 0.9517, 0.3402],
        [0.3098, 0.9517, 0.3402],
        [0.8465, 0.3194, 0.5687],
        [0.9843, 0.0353, 0.4146],
        [0.2481, 0.6432, 0.3115],
        [0.9843, 0.0353, 0.4146],
        [0.2481, 0.6432, 0.3115],
        [0.984